#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx


mkdir /var/www/html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton Schools" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;

    add_header X-Served-By $HOSTNAME;

    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.zaharaschool.com;
        }
    eror_page 404 /404.html;
    location /404 {
        root /var/www/html
        internal;
        }
    }" > /etc/nginx/sites-available/default

service nginx restart