#!/usr/bin/env bash
#process and pid
#shellcheck disable=SC2009

terminate() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while :
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminate' SIGTERM
  trap 'terminate' SIGQUIT
done
