#!/usr/bin/env bash
#process and pid
#shellcheck disable=SC2009

terminate()
{
if[ -e "/var/run/myscript.pid ]
rm /var/run/myscript.pid
exit
fi
}

echo $$ > /var/run/myscript.pid
while :
do
echo To infinity and beyond
sleep 2
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command" && terminate' SIGTERM 
trap 'terminate' SIGQUIT
done
