#!/usr/bin/env bash
#kill process without kill, killall but pkill
#pkill directly matches against process name while f matches against all arguments in 4-to_infinity_and_beyond

pkill -f 4-to_infinity_and_beyond
