#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format
#diplays "FizzBuzz" when the number is a multiple of 3 and 5
# displays "Fizz" when the number is a multiple of 3
# Displays "Buzz" when number is a multiple of 5
#else, displays the number

