#!/usr/bin/env bash
#displays best school ten times
i=0

while [ $i -le 10 ]
do
((i++))
    if [[ "$i" == '4' ]]; then
    echo bad luck
    elif [[ "$i" == '8' ]]; then
    echo good luck
    else
    echo Best School
    fi
done
