#!/usr/bin/env bash
i=1

while [ $i -lt  21 ]
do
    echo $i
    ((i++))
    if [[ "$i" == '4' ]]; then
    echo $i
    echo bad luck from China
    elif [[ "$i" == '9' ]]; then
    echo $i 
    echo bad luck from Japan
    elif [[ "$i" == '17' ]]; then
    echo $i 
    echo bad luck from Italy

  fi
done
