#!/usr/bin/env bash
#it changes the ip address of localhost and facebook
#because docker treats etc/hosts without any regards for modifications
#cp /etc/hosts ~/hosts.new
#sed ... ~/hosts.new
#cp -f ~/hosts.new /etc/hosts

cp /etc/hosts ~/hosts.new
127.0.0.2 localhost
8.8.8.8 facebook.com
cp -f ~/hosts.new /etc/hosts
