#!/usr/bin/env bash
#it changes the ip address of localhost and facebook
#host file(/etc/hosts) resolves or translates hostnames to ip address
#because docker treats etc/hosts without any regards for modifications, line 6 and 9 should be there

cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" > ~/hosts.new
cp -f ~/hosts.new /etc/hosts
